import Nav from "@/components/Nav/Nav";
import Providers from "@/lib/utils/Providers/Provider.client";
import { AppRoutes } from "@/lib/utils/constants/AppRoutes";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { authOptions } from "../../auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TodoApp",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-primary text-black min-h-screen font-medium`}
      >
        {/* HEADER */}
        <header className="flex justify-between items-center p-4">
          <h1 className="text-2xl text-center uppercase text-black font-semibold">
            <Link href={AppRoutes.Home}>TodoApp</Link>
          </h1>
          <Nav session={session} />
        </header>

        {/* CONTENT */}
        <main className="flex h-[75vh] flex-col items-center px-4 overflow-auto">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
